use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::Parser;

#[derive(Debug, Parser)]
#[command(name = "tunasync-netns-broker", version)]
struct Cli {
    /// Root-owned JSON policy generated by `tunasync worker --emit-netns-policy`.
    #[arg(long, default_value = "/etc/tunasync/netns-policy.json")]
    config: PathBuf,
    /// Unix socket exposed to the unprivileged worker.
    #[arg(long, default_value = tunasync_netns::DEFAULT_SOCKET)]
    socket: PathBuf,
    /// Exact worker user name or numeric UID; children are also dropped to it.
    #[arg(long, default_value = "tunasync")]
    uid: String,
    /// Worker group name or numeric GID; owns the socket and child processes.
    #[arg(long, default_value = "tunasync")]
    gid: String,
    /// Unix socket mode in octal.
    #[arg(long, default_value = "0660", value_parser = parse_octal_mode)]
    socket_mode: u32,
    /// Maximum simultaneously admitted client connections.
    #[arg(long, default_value_t = 32, value_parser = parse_max_connections)]
    max_connections: usize,
    /// Maximum simultaneously supervised namespace jobs.
    #[arg(long, default_value_t = 8, value_parser = parse_max_jobs)]
    max_jobs: usize,
    /// Seconds allowed to deliver the first complete request frame.
    #[arg(long, default_value_t = 5, value_parser = clap::value_parser!(u64).range(1..=300))]
    read_timeout: u64,
    /// Validate identity, namespace pins, and policy, then exit.
    #[arg(long)]
    check: bool,
    #[arg(long, hide = true)]
    launcher_helper: bool,
    #[arg(long, hide = true)]
    seccomp_test_helper: bool,
    #[arg(long, hide = true)]
    privileged_smoke_helper: bool,
    #[arg(long, hide = true, requires = "privileged_smoke_helper")]
    smoke_namespace: Option<String>,
    #[arg(long, hide = true, requires = "privileged_smoke_helper")]
    smoke_target: Option<PathBuf>,
}

fn parse_octal_mode(value: &str) -> std::result::Result<u32, String> {
    let mode = u32::from_str_radix(value.trim_start_matches("0o"), 8)
        .map_err(|_| format!("invalid octal socket mode {value:?}"))?;
    if mode > 0o666 || mode & 0o111 != 0 {
        return Err("socket mode must be within 0000..0666 and non-executable".into());
    }
    Ok(mode)
}

fn parse_max_connections(value: &str) -> std::result::Result<usize, String> {
    parse_bounded_usize(value, 1, 4096, "max connections")
}

fn parse_max_jobs(value: &str) -> std::result::Result<usize, String> {
    parse_bounded_usize(value, 1, 1024, "max jobs")
}

fn parse_bounded_usize(
    value: &str,
    minimum: usize,
    maximum: usize,
    field: &str,
) -> std::result::Result<usize, String> {
    let parsed = value
        .parse::<usize>()
        .map_err(|_| format!("invalid {field} {value:?}"))?;
    if (minimum..=maximum).contains(&parsed) {
        Ok(parsed)
    } else {
        Err(format!("{field} must be in {minimum}..={maximum}"))
    }
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    if !cli.launcher_helper && !cli.seccomp_test_helper && !cli.privileged_smoke_helper {
        tracing_subscriber::fmt()
            .with_target(false)
            .without_time()
            .compact()
            .init();
    }
    platform::run(cli)
}

#[cfg(not(target_os = "linux"))]
mod platform {
    use super::*;

    pub fn run(_cli: Cli) -> Result<()> {
        anyhow::bail!("tunasync-netns-broker is only functional on Linux")
    }
}

#[cfg(target_os = "linux")]
mod platform {
    use std::collections::{HashMap, HashSet};
    use std::ffi::{CStr, CString};
    use std::fs::File;
    use std::io::Read;
    use std::os::fd::{AsRawFd, FromRawFd, OwnedFd, RawFd};
    use std::os::unix::ffi::OsStrExt;
    use std::os::unix::fs::{FileTypeExt, MetadataExt, OpenOptionsExt, PermissionsExt};
    use std::os::unix::net::{UnixListener, UnixStream};
    use std::process::{Child, Command, ExitStatus, Stdio};
    use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
    use std::sync::{mpsc, Arc, Mutex};
    use std::thread::JoinHandle;
    use std::time::{Duration, Instant};

    use serde::{Deserialize, Serialize};
    use sha2::{Digest, Sha256};
    use tunasync_netns::{ClientRequest, LaunchRequest, Policy, ServerFrame, MAX_OUTPUT_CHUNK};

    use super::*;

    const HELPER_SECRET_ENV: &str = "TUNASYNC_NETNS_HELPER_SECRET";
    const OUTPUT_QUEUE: usize = 64;
    const CLEANUP_GRACE: Duration = Duration::from_secs(2);
    const READER_JOIN_TIMEOUT: Duration = Duration::from_secs(2);

    #[derive(Debug, Clone, Copy)]
    struct PeerCred {
        uid: u32,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
    struct FileIdentity {
        dev: u64,
        ino: u64,
    }

    #[derive(Debug)]
    struct RuntimePolicy {
        policy: Policy,
        sha256: String,
        namespaces: HashMap<String, FileIdentity>,
    }

    struct PolicyStore {
        path: PathBuf,
        current: Mutex<Arc<RuntimePolicy>>,
    }

    impl PolicyStore {
        fn new(path: PathBuf, initial: RuntimePolicy) -> Self {
            Self {
                path,
                current: Mutex::new(Arc::new(initial)),
            }
        }

        fn snapshot(&self) -> Result<Arc<RuntimePolicy>> {
            let loaded = load_policy(&self.path, true, true)?;
            let mut current = self.current.lock().unwrap();
            if loaded.sha256 != current.sha256 {
                if loaded.policy.generation == current.policy.generation {
                    anyhow::bail!(
                        "policy content changed without changing generation {:?}",
                        loaded.policy.generation
                    );
                }
                tracing::info!(
                    old_generation = %current.policy.generation,
                    new_generation = %loaded.policy.generation,
                    "reloaded netns policy"
                );
                *current = Arc::new(loaded);
            } else {
                current.verify_namespace_pins()?;
            }
            Ok(Arc::clone(&current))
        }
    }

    impl RuntimePolicy {
        fn verify_namespace_pins(&self) -> Result<()> {
            for (name, expected) in &self.namespaces {
                let fd = open_namespace(name)?;
                let actual = fd_identity(fd.as_raw_fd())?;
                if &actual != expected {
                    anyhow::bail!(
                        "network namespace {name:?} was replaced under policy generation {:?}",
                        self.policy.generation
                    );
                }
            }
            Ok(())
        }
    }

    #[derive(Debug)]
    enum SupervisorControl {
        Terminate(mpsc::Sender<()>),
    }

    #[derive(Clone)]
    struct JobEntry {
        uid: u32,
        key: (String, String),
        exclusive: bool,
        control: mpsc::Sender<SupervisorControl>,
    }

    #[derive(Default)]
    struct JobRegistry {
        jobs: HashMap<String, JobEntry>,
        active_keys: HashSet<(String, String)>,
    }

    struct Shared {
        uid: u32,
        gid: u32,
        max_jobs: usize,
        read_timeout: Duration,
        policy: PolicyStore,
        jobs: Mutex<JobRegistry>,
    }

    struct ConnectionPermit(Arc<AtomicUsize>);

    impl Drop for ConnectionPermit {
        fn drop(&mut self) {
            self.0.fetch_sub(1, Ordering::Release);
        }
    }

    #[derive(Debug, Serialize, Deserialize)]
    struct HelperPayload {
        secret: String,
        policy_sha256: String,
        namespace_identity: FileIdentity,
        request: LaunchRequest,
        uid: u32,
        gid: u32,
    }

    pub fn run(cli: Cli) -> Result<()> {
        if cli.launcher_helper {
            return run_launcher_helper(&cli);
        }
        if cli.seccomp_test_helper {
            return run_seccomp_test_helper();
        }
        if cli.privileged_smoke_helper {
            return run_privileged_smoke_helper(&cli);
        }
        verify_required_kernel_syscalls()?;
        let uid = resolve_uid(&cli.uid)?;
        let gid = resolve_gid(&cli.gid)?;
        if uid == 0 || gid == 0 {
            anyhow::bail!("worker uid and gid must both be non-zero");
        }
        let policy = load_policy(&cli.config, true, true)?;
        if cli.check {
            println!(
                "{}: OK - generation {}, {} launch plan(s), {} namespace pin(s)",
                cli.config.display(),
                policy.policy.generation,
                policy.policy.launch.len(),
                policy.namespaces.len()
            );
            return Ok(());
        }
        // SAFETY: geteuid has no pointer arguments or preconditions.
        if unsafe { libc::geteuid() } != 0 {
            anyhow::bail!("broker must run as root")
        }
        let shared = Arc::new(Shared {
            uid,
            gid,
            max_jobs: cli.max_jobs,
            read_timeout: Duration::from_secs(cli.read_timeout),
            policy: PolicyStore::new(cli.config.clone(), policy),
            jobs: Mutex::new(JobRegistry::default()),
        });
        bind_and_serve(&cli.socket, cli.socket_mode, cli.max_connections, shared)
    }

    fn load_policy(
        path: &std::path::Path,
        require_root_control: bool,
        pin_namespaces: bool,
    ) -> Result<RuntimePolicy> {
        let mut file = std::fs::OpenOptions::new()
            .read(true)
            .custom_flags(libc::O_CLOEXEC | libc::O_NOFOLLOW)
            .open(path)
            .with_context(|| format!("open policy {}", path.display()))?;
        let metadata = file
            .metadata()
            .with_context(|| format!("stat policy {}", path.display()))?;
        if !metadata.is_file() {
            anyhow::bail!("policy {} is not a regular file", path.display());
        }
        if require_root_control
            && (metadata.uid() != 0 || metadata.permissions().mode() & 0o022 != 0)
        {
            anyhow::bail!(
                "policy {} must be root-owned and not group/other writable",
                path.display()
            );
        }
        let mut bytes = Vec::new();
        std::io::Read::by_ref(&mut file)
            .take((tunasync_netns::MAX_FRAME_LEN + 1) as u64)
            .read_to_end(&mut bytes)
            .with_context(|| format!("read policy {}", path.display()))?;
        if bytes.len() > tunasync_netns::MAX_FRAME_LEN {
            anyhow::bail!("policy exceeds {} bytes", tunasync_netns::MAX_FRAME_LEN);
        }
        let policy: Policy = serde_json::from_slice(&bytes).context("parse policy JSON")?;
        policy.validate().map_err(anyhow::Error::msg)?;
        let sha256 = hex_digest(&bytes);
        let mut namespaces = HashMap::new();
        if pin_namespaces && !policy.launch.is_empty() {
            validate_netns_root()?;
            for entry in &policy.launch {
                if !namespaces.contains_key(&entry.namespace) {
                    let fd = open_namespace(&entry.namespace)?;
                    namespaces.insert(entry.namespace.clone(), fd_identity(fd.as_raw_fd())?);
                }
            }
        }
        Ok(RuntimePolicy {
            policy,
            sha256,
            namespaces,
        })
    }

    fn bind_and_serve(
        socket: &std::path::Path,
        socket_mode: u32,
        max_connections: usize,
        shared: Arc<Shared>,
    ) -> Result<()> {
        let parent = socket
            .parent()
            .context("broker socket must have a parent directory")?;
        std::fs::create_dir_all(parent)
            .with_context(|| format!("create socket directory {}", parent.display()))?;
        let parent_meta = std::fs::symlink_metadata(parent)?;
        if !parent_meta.is_dir()
            || parent_meta.file_type().is_symlink()
            || parent_meta.uid() != 0
            || parent_meta.permissions().mode() & 0o022 != 0
        {
            anyhow::bail!(
                "socket directory {} must be a root-owned directory not writable by group/other",
                parent.display()
            );
        }
        if socket.exists() {
            let meta = std::fs::symlink_metadata(socket)?;
            if !meta.file_type().is_socket() {
                anyhow::bail!("refusing to replace non-socket {}", socket.display());
            }
            std::fs::remove_file(socket)?;
        }
        let listener = UnixListener::bind(socket)
            .with_context(|| format!("bind broker socket {}", socket.display()))?;
        let c_socket = CString::new(socket.as_os_str().as_bytes())?;
        // SAFETY: c_socket is a live, NUL-terminated path and remains valid
        // for the duration of the chown call.
        if unsafe { libc::chown(c_socket.as_ptr(), 0, shared.gid) } != 0 {
            return Err(std::io::Error::last_os_error()).context("chown broker socket");
        }
        std::fs::set_permissions(socket, std::fs::Permissions::from_mode(socket_mode))?;
        let generation = shared.policy.snapshot()?.policy.generation.clone();
        tracing::info!(
            path = %socket.display(),
            worker_uid = shared.uid,
            worker_gid = shared.gid,
            %generation,
            max_connections,
            max_jobs = shared.max_jobs,
            "broker listening"
        );

        let connections = Arc::new(AtomicUsize::new(0));
        for stream in listener.incoming() {
            match stream {
                Ok(mut stream) => {
                    let previous = connections.fetch_add(1, Ordering::AcqRel);
                    if previous >= max_connections {
                        connections.fetch_sub(1, Ordering::Release);
                        send_error(&mut stream, "busy", "broker connection limit reached");
                        continue;
                    }
                    let permit = ConnectionPermit(Arc::clone(&connections));
                    let shared = Arc::clone(&shared);
                    std::thread::spawn(move || {
                        let _permit = permit;
                        if let Err(error) = handle_connection(stream, &shared) {
                            tracing::warn!(error = %error, "broker request rejected");
                        }
                    });
                }
                Err(error) => tracing::error!(error = %error, "accept failed"),
            }
        }
        Ok(())
    }

    fn handle_connection(mut stream: UnixStream, shared: &Arc<Shared>) -> Result<()> {
        stream.set_read_timeout(Some(shared.read_timeout))?;
        stream.set_write_timeout(Some(Duration::from_secs(2)))?;
        let peer = peer_cred(&stream)?;
        if peer.uid != shared.uid {
            anyhow::bail!("peer uid {} is not authorized", peer.uid);
        }
        let request: ClientRequest = tunasync_netns::read_frame(&mut stream)?;
        stream.set_read_timeout(None)?;
        match request {
            ClientRequest::Status => {
                let policy = shared.policy.snapshot().inspect_err(|error| {
                    send_error(&mut stream, "policy", &error.to_string());
                })?;
                tunasync_netns::write_frame(
                    &mut stream,
                    &ServerFrame::Ready {
                        generation: policy.policy.generation.clone(),
                    },
                )?;
                Ok(())
            }
            ClientRequest::Launch(request) => {
                let policy = shared.policy.snapshot().inspect_err(|error| {
                    send_error(&mut stream, "policy", &error.to_string());
                })?;
                if let Err(message) = policy.policy.authorize(&request) {
                    send_error(&mut stream, "policy", &message);
                    anyhow::bail!(message);
                }
                run_authorized(stream, peer, shared, policy, request)
            }
            ClientRequest::Terminate { job_id } => {
                terminate_authorized(&mut stream, peer, &job_id, shared)
            }
        }
    }

    fn run_authorized(
        mut stream: UnixStream,
        peer: PeerCred,
        shared: &Arc<Shared>,
        policy: Arc<RuntimePolicy>,
        request: LaunchRequest,
    ) -> Result<()> {
        let entry = policy
            .policy
            .launch
            .iter()
            .find(|entry| {
                entry.mirror == request.mirror
                    && entry.operation == request.operation
                    && entry.namespace == request.namespace
            })
            .context("authorized policy entry disappeared")?;
        let namespace_identity = *policy
            .namespaces
            .get(&request.namespace)
            .context("authorized namespace pin missing")?;
        let job_id = random_hex(32)?;
        let key = (request.mirror.clone(), request.operation.clone());
        let (control_tx, control_rx) = mpsc::channel();
        {
            let mut registry = shared.jobs.lock().unwrap();
            if registry.jobs.len() >= shared.max_jobs {
                send_error(&mut stream, "busy", "broker job limit reached");
                anyhow::bail!("broker job limit reached");
            }
            if !entry.allow_concurrency && registry.active_keys.contains(&key) {
                send_error(
                    &mut stream,
                    "busy",
                    "mirror operation already has an active namespace job",
                );
                anyhow::bail!("duplicate mirror operation is busy");
            }
            if !entry.allow_concurrency {
                registry.active_keys.insert(key.clone());
            }
            registry.jobs.insert(
                job_id.clone(),
                JobEntry {
                    uid: peer.uid,
                    key: key.clone(),
                    exclusive: !entry.allow_concurrency,
                    control: control_tx,
                },
            );
        }

        let spawn = spawn_helper(shared, &policy, namespace_identity, request);
        let child = match spawn {
            Ok(child) => child,
            Err(error) => {
                remove_job(shared, &job_id, &key);
                send_error(&mut stream, "spawn", &error.to_string());
                return Err(error);
            }
        };
        let pid = child.id();
        let mut supervisor =
            match Supervisor::new(child, shared, job_id.clone(), key.clone(), control_rx) {
                Ok(supervisor) => supervisor,
                Err((mut child, error)) => {
                    terminate_and_reap(&mut child);
                    remove_job(shared, &job_id, &key);
                    send_error(&mut stream, "spawn", &error.to_string());
                    return Err(error);
                }
            };
        if tunasync_netns::write_frame(
            &mut stream,
            &ServerFrame::Started {
                job_id: job_id.clone(),
                pid,
            },
        )
        .is_err()
        {
            supervisor.cleanup();
            return Ok(());
        }
        supervisor.relay(&mut stream)
    }

    fn spawn_helper(
        shared: &Shared,
        policy: &RuntimePolicy,
        namespace_identity: FileIdentity,
        request: LaunchRequest,
    ) -> Result<Child> {
        let secret = random_hex(32)?;
        let payload = HelperPayload {
            secret: secret.clone(),
            policy_sha256: policy.sha256.clone(),
            namespace_identity,
            request,
            uid: shared.uid,
            gid: shared.gid,
        };
        let exe = std::env::current_exe().context("resolve broker executable")?;
        let mut child = Command::new(exe)
            .arg("--launcher-helper")
            .arg("--config")
            .arg(&shared.policy.path)
            .arg("--uid")
            .arg(shared.uid.to_string())
            .arg("--gid")
            .arg(shared.gid.to_string())
            .env_clear()
            .env(HELPER_SECRET_ENV, &secret)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .context("spawn clean launcher helper")?;
        let mut stdin = child
            .stdin
            .take()
            .context("launcher helper stdin missing")?;
        if let Err(error) = tunasync_netns::write_frame(&mut stdin, &payload) {
            terminate_and_reap(&mut child);
            return Err(error.into());
        }
        drop(stdin);
        Ok(child)
    }

    struct Supervisor<'a> {
        child: Child,
        pgid: i32,
        shared: &'a Shared,
        job_id: String,
        key: (String, String),
        control: mpsc::Receiver<SupervisorControl>,
        output_rx: mpsc::Receiver<ServerFrame>,
        readers: Vec<JoinHandle<()>>,
        reader_cancel: Arc<AtomicBool>,
        cleaned: bool,
    }

    impl<'a> Supervisor<'a> {
        fn new(
            mut child: Child,
            shared: &'a Shared,
            job_id: String,
            key: (String, String),
            control: mpsc::Receiver<SupervisorControl>,
        ) -> std::result::Result<Self, (Child, anyhow::Error)> {
            let pgid = child.id() as i32;
            let Some(stdout) = child.stdout.take() else {
                return Err((child, anyhow::anyhow!("helper stdout missing")));
            };
            let Some(stderr) = child.stderr.take() else {
                return Err((child, anyhow::anyhow!("helper stderr missing")));
            };
            let (output_tx, output_rx) = mpsc::sync_channel(OUTPUT_QUEUE);
            let reader_cancel = Arc::new(AtomicBool::new(false));
            let readers = vec![
                spawn_output_reader(stdout, output_tx.clone(), true, Arc::clone(&reader_cancel)),
                spawn_output_reader(stderr, output_tx, false, Arc::clone(&reader_cancel)),
            ];
            Ok(Self {
                child,
                pgid,
                shared,
                job_id,
                key,
                control,
                output_rx,
                readers,
                reader_cancel,
                cleaned: false,
            })
        }

        fn relay(&mut self, stream: &mut UnixStream) -> Result<()> {
            loop {
                while let Ok(frame) = self.output_rx.try_recv() {
                    if tunasync_netns::write_frame(stream, &frame).is_err() {
                        self.cleanup();
                        return Ok(());
                    }
                }
                match self.control.try_recv() {
                    Ok(SupervisorControl::Terminate(reply)) => {
                        self.cleanup();
                        let _ = reply.send(());
                        return Ok(());
                    }
                    Err(mpsc::TryRecvError::Disconnected) => {}
                    Err(mpsc::TryRecvError::Empty) => {}
                }
                if peer_has_event(stream)? {
                    self.cleanup();
                    return Ok(());
                }
                if let Some(status) = self.child.try_wait()? {
                    self.finish_after_exit(status, stream);
                    return Ok(());
                }
                std::thread::sleep(Duration::from_millis(20));
            }
        }

        fn finish_after_exit(&mut self, status: ExitStatus, stream: &mut UnixStream) {
            terminate_group_only(self.pgid, Duration::from_millis(200));
            self.drain_and_join_readers();
            let (code, signal) = exit_parts(status);
            remove_job(self.shared, &self.job_id, &self.key);
            self.cleaned = true;
            let _ = tunasync_netns::write_frame(stream, &ServerFrame::Exit { code, signal });
        }

        fn cleanup(&mut self) {
            if self.cleaned {
                return;
            }
            terminate_group(self.pgid, CLEANUP_GRACE);
            let _ = self.child.wait();
            self.drain_and_join_readers();
            remove_job(self.shared, &self.job_id, &self.key);
            self.cleaned = true;
        }

        fn drain_and_join_readers(&mut self) {
            self.reader_cancel.store(true, Ordering::Release);
            let deadline = Instant::now() + READER_JOIN_TIMEOUT;
            while Instant::now() < deadline
                && self.readers.iter().any(|reader| !reader.is_finished())
            {
                while self.output_rx.try_recv().is_ok() {}
                std::thread::sleep(Duration::from_millis(10));
            }
            while self.output_rx.try_recv().is_ok() {}
            for reader in self.readers.drain(..) {
                let _ = reader.join();
            }
        }
    }

    impl Drop for Supervisor<'_> {
        fn drop(&mut self) {
            self.cleanup();
        }
    }

    fn spawn_output_reader<R: Read + AsRawFd + Send + 'static>(
        mut reader: R,
        tx: mpsc::SyncSender<ServerFrame>,
        stdout: bool,
        cancel: Arc<AtomicBool>,
    ) -> JoinHandle<()> {
        std::thread::spawn(move || {
            let mut buf = vec![0_u8; MAX_OUTPUT_CHUNK];
            loop {
                if cancel.load(Ordering::Acquire) {
                    break;
                }
                let mut pollfd = libc::pollfd {
                    fd: reader.as_raw_fd(),
                    events: libc::POLLIN | libc::POLLHUP | libc::POLLERR,
                    revents: 0,
                };
                // SAFETY: pollfd points to one initialized pollfd value for
                // the entire call; reader owns the referenced open fd.
                let poll = unsafe { libc::poll(&mut pollfd, 1, 100) };
                if poll == 0 {
                    continue;
                }
                if poll < 0 {
                    break;
                }
                match reader.read(&mut buf) {
                    Ok(0) => break,
                    Ok(n) => {
                        let frame = if stdout {
                            ServerFrame::Stdout {
                                data: buf[..n].to_vec(),
                            }
                        } else {
                            ServerFrame::Stderr {
                                data: buf[..n].to_vec(),
                            }
                        };
                        match tx.try_send(frame) {
                            Ok(()) | Err(mpsc::TrySendError::Full(_)) => {
                                // Output is best-effort under backpressure: drop
                                // the newest frame rather than ever blocking a
                                // pipe reader behind a slow worker connection.
                            }
                            Err(mpsc::TrySendError::Disconnected(_)) => break,
                        }
                    }
                    Err(_) => break,
                }
            }
        })
    }

    fn terminate_authorized(
        stream: &mut UnixStream,
        peer: PeerCred,
        job_id: &str,
        shared: &Shared,
    ) -> Result<()> {
        let entry = shared.jobs.lock().unwrap().jobs.get(job_id).cloned();
        let Some(entry) = entry.filter(|entry| entry.uid == peer.uid) else {
            send_error(stream, "auth", "unknown job capability for this worker uid");
            anyhow::bail!("terminate authorization failed");
        };
        let (reply_tx, reply_rx) = mpsc::channel();
        entry
            .control
            .send(SupervisorControl::Terminate(reply_tx))
            .context("job supervisor is no longer available")?;
        reply_rx
            .recv_timeout(CLEANUP_GRACE + READER_JOIN_TIMEOUT + Duration::from_secs(1))
            .context("job supervisor cleanup timed out")?;
        tunasync_netns::write_frame(stream, &ServerFrame::Terminated)?;
        Ok(())
    }

    fn remove_job(shared: &Shared, job_id: &str, key: &(String, String)) {
        let mut registry = shared.jobs.lock().unwrap();
        if let Some(entry) = registry.jobs.remove(job_id) {
            if entry.exclusive && &entry.key == key {
                registry.active_keys.remove(key);
            }
        }
    }

    fn run_launcher_helper(cli: &Cli) -> Result<()> {
        // SAFETY: geteuid has no pointer arguments or preconditions.
        if unsafe { libc::geteuid() } != 0 {
            anyhow::bail!("launcher helper requires effective uid 0");
        }
        let inherited_secret = std::env::var(HELPER_SECRET_ENV)
            .context("launcher helper authorization secret is missing")?;
        std::env::remove_var(HELPER_SECRET_ENV);
        if inherited_secret.len() != 64
            || !inherited_secret
                .bytes()
                .all(|byte| byte.is_ascii_hexdigit())
        {
            anyhow::bail!("launcher helper authorization secret is invalid");
        }
        let payload: HelperPayload = tunasync_netns::read_frame(&mut std::io::stdin().lock())?;
        if !constant_time_eq(payload.secret.as_bytes(), inherited_secret.as_bytes()) {
            anyhow::bail!("launcher helper authorization secret mismatch");
        }
        let uid = resolve_uid(&cli.uid)?;
        let gid = resolve_gid(&cli.gid)?;
        if uid == 0 || gid == 0 || payload.uid != uid || payload.gid != gid {
            anyhow::bail!("launcher helper target identity mismatch");
        }
        let runtime = load_policy(&cli.config, true, true)?;
        if runtime.sha256 != payload.policy_sha256 {
            anyhow::bail!("launcher helper policy identity mismatch");
        }
        runtime
            .policy
            .authorize(&payload.request)
            .map_err(anyhow::Error::msg)?;
        let expected = runtime
            .namespaces
            .get(&payload.request.namespace)
            .context("launcher helper namespace pin missing")?;
        if expected != &payload.namespace_identity {
            anyhow::bail!("launcher helper namespace authorization identity mismatch");
        }
        launch_pinned(payload.request, payload.namespace_identity, uid, gid)
    }

    fn launch_pinned(
        request: LaunchRequest,
        expected_namespace: FileIdentity,
        uid: u32,
        gid: u32,
    ) -> Result<()> {
        let namespace_fd = open_namespace(&request.namespace)?;
        if fd_identity(namespace_fd.as_raw_fd())? != expected_namespace {
            anyhow::bail!("network namespace changed after authorization");
        }
        let cwd_fd = open_directory(&request.plan.cwd)?;
        let executable_fd = open_executable(&request.plan.argv[0])?;
        let argv = cstring_vec(&request.plan.argv, "argv")?;
        let mut environment = request
            .plan
            .env
            .iter()
            .map(|(key, value)| format!("{key}={value}"))
            .collect::<Vec<_>>();
        environment
            .push("PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin".into());
        environment.push("LANG=C".into());
        environment.push("LC_ALL=C".into());
        let env = cstring_vec(&environment, "environment")?;
        let argv_ptrs = cstring_ptrs(&argv);
        let env_ptrs = cstring_ptrs(&env);

        // SAFETY: pid 0 and pgid 0 are the documented self/new-group
        // sentinels; this runs before the target seccomp filter is installed.
        if unsafe { libc::setpgid(0, 0) } != 0 {
            return Err(std::io::Error::last_os_error()).context("set launcher process group");
        }
        // SAFETY: namespace_fd is an owned fd pinned to a verified network
        // namespace and CLONE_NEWNET selects the matching namespace type.
        if unsafe { libc::setns(namespace_fd.as_raw_fd(), libc::CLONE_NEWNET) } != 0 {
            return Err(std::io::Error::last_os_error()).context("enter network namespace");
        }
        // SAFETY: cwd_fd is an owned descriptor opened as a directory.
        if unsafe { libc::fchdir(cwd_fd.as_raw_fd()) } != 0 {
            return Err(std::io::Error::last_os_error()).context("enter working directory");
        }
        drop(namespace_fd);
        drop(cwd_fd);
        // SAFETY: a zero group count requires no backing array; null is the
        // documented pointer value for clearing supplementary groups.
        if unsafe { libc::setgroups(0, std::ptr::null()) } != 0 {
            return Err(std::io::Error::last_os_error()).context("clear supplementary groups");
        }
        drop_capability_bounding_set().context("drop capability bounding set")?;
        // SAFETY: gid was resolved and validated as a non-root target identity.
        if unsafe { libc::setresgid(gid, gid, gid) } != 0 {
            return Err(std::io::Error::last_os_error()).context("drop gid");
        }
        // SAFETY: uid was resolved and validated as a non-root target identity.
        if unsafe { libc::setresuid(uid, uid, uid) } != 0 {
            return Err(std::io::Error::last_os_error()).context("drop uid");
        }
        clear_capabilities().context("clear capabilities")?;
        // SAFETY: PR_CAP_AMBIENT_CLEAR_ALL takes no pointer arguments; the
        // remaining zero arguments are required by the prctl ABI.
        if unsafe {
            libc::prctl(
                libc::PR_CAP_AMBIENT,
                libc::PR_CAP_AMBIENT_CLEAR_ALL,
                0,
                0,
                0,
            )
        } != 0
        {
            return Err(std::io::Error::last_os_error()).context("clear ambient capabilities");
        }
        // SAFETY: PR_SET_NO_NEW_PRIVS accepts scalar arguments only; setting
        // it to 1 is irreversible for this process tree.
        if unsafe { libc::prctl(libc::PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0) } != 0 {
            return Err(std::io::Error::last_os_error()).context("set no_new_privs");
        }
        sanitize_fds(executable_fd.as_raw_fd()).context("sanitize launcher file descriptors")?;
        // Isolated targets, including descendants, must remain in the
        // broker-owned process group. Daemonization, setsid(), and setpgid()
        // are intentionally unsupported so cleanup can always kill and reap
        // the complete target tree.
        install_process_group_seccomp().context("install process-group seccomp filter")?;
        let empty = c"";
        // SAFETY: executable_fd pins a verified ELF; empty is a valid empty C
        // path for AT_EMPTY_PATH; argv/env pointer arrays are NUL-terminated
        // and their CString storage remains live until the syscall returns.
        let result = unsafe {
            libc::syscall(
                libc::SYS_execveat,
                executable_fd.as_raw_fd(),
                empty.as_ptr(),
                argv_ptrs.as_ptr(),
                env_ptrs.as_ptr(),
                libc::AT_EMPTY_PATH,
            )
        };
        debug_assert_eq!(result, -1);
        Err(std::io::Error::last_os_error()).context("exec pinned ELF executable")
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    enum RequiredSyscallError {
        Unsupported,
        Blocked,
        Unexpected,
    }

    fn classify_required_syscall_error(error: &std::io::Error) -> RequiredSyscallError {
        match error.raw_os_error() {
            Some(libc::ENOSYS) => RequiredSyscallError::Unsupported,
            Some(libc::EPERM) => RequiredSyscallError::Blocked,
            _ => RequiredSyscallError::Unexpected,
        }
    }

    fn required_syscall_error(name: &str, error: std::io::Error) -> anyhow::Error {
        let reason = match classify_required_syscall_error(&error) {
            RequiredSyscallError::Unsupported => "is not implemented by this kernel",
            RequiredSyscallError::Blocked => "is blocked by the service/container syscall policy",
            RequiredSyscallError::Unexpected => "failed its security probe",
        };
        anyhow::anyhow!(
            "required syscall {name} {reason}: {error}; tunasync-netns-broker requires Linux kernel >= 5.6 with openat2 and execveat enabled"
        )
    }

    fn verify_required_kernel_syscalls() -> Result<()> {
        let root = open_raw(c"/", libc::O_PATH | libc::O_DIRECTORY | libc::O_CLOEXEC)
            .context("open root for openat2 probe")?;
        let how = OpenHow {
            flags: (libc::O_PATH | libc::O_DIRECTORY | libc::O_CLOEXEC) as u64,
            mode: 0,
            resolve: RESOLVE_BENEATH | RESOLVE_NO_MAGICLINKS | RESOLVE_NO_SYMLINKS,
        };
        // SAFETY: root is an open directory fd, the path and OpenHow pointers
        // remain valid for the call, and the kernel receives the exact ABI size.
        let fd = unsafe {
            libc::syscall(
                libc::SYS_openat2,
                root.as_raw_fd(),
                c".".as_ptr(),
                &how,
                std::mem::size_of::<OpenHow>(),
            )
        } as i32;
        if fd < 0 {
            return Err(required_syscall_error(
                "openat2(2)",
                std::io::Error::last_os_error(),
            ));
        }
        // SAFETY: fd is a newly returned, non-negative descriptor owned by us.
        drop(unsafe { OwnedFd::from_raw_fd(fd) });

        let empty_vector = [std::ptr::null::<libc::c_char>()];
        // SAFETY: fd -1 deliberately forces EBADF; the empty path is valid and
        // argv/env are live NUL-terminated pointer arrays, so the probe tests
        // syscall availability without replacing the current process.
        let result = unsafe {
            libc::syscall(
                libc::SYS_execveat,
                -1,
                c"".as_ptr(),
                empty_vector.as_ptr(),
                empty_vector.as_ptr(),
                libc::AT_EMPTY_PATH,
            )
        };
        if result == -1 {
            let error = std::io::Error::last_os_error();
            if error.raw_os_error() != Some(libc::EBADF) {
                return Err(required_syscall_error("execveat(2)", error));
            }
        }
        Ok(())
    }

    const BPF_LD_W_ABS: u16 = 0x20;
    const BPF_JMP_JEQ_K: u16 = 0x15;
    const BPF_RET_K: u16 = 0x06;
    const SECCOMP_RET_KILL_PROCESS: u32 = 0x8000_0000;
    const SECCOMP_RET_ERRNO: u32 = 0x0005_0000;
    const SECCOMP_RET_ALLOW: u32 = 0x7fff_0000;

    fn audit_arch() -> u32 {
        #[cfg(target_arch = "x86_64")]
        return 0xc000_003e;
        #[cfg(target_arch = "aarch64")]
        return 0xc000_00b7;
        #[cfg(target_arch = "arm")]
        return 0x4000_0028;
        #[cfg(target_arch = "riscv64")]
        return 0xc000_00f3;
        #[cfg(target_arch = "loongarch64")]
        return 0xc000_0102;
        #[cfg(not(any(
            target_arch = "x86_64",
            target_arch = "aarch64",
            target_arch = "arm",
            target_arch = "riscv64",
            target_arch = "loongarch64"
        )))]
        compile_error!("unsupported Linux architecture for netns broker seccomp");
    }

    fn process_group_seccomp_filter() -> Vec<libc::sock_filter> {
        let statement = |code, k| libc::sock_filter {
            code,
            jt: 0,
            jf: 0,
            k,
        };
        let jump = |k, jt, jf| libc::sock_filter {
            code: BPF_JMP_JEQ_K,
            jt,
            jf,
            k,
        };
        vec![
            statement(BPF_LD_W_ABS, 4),
            jump(audit_arch(), 1, 0),
            statement(BPF_RET_K, SECCOMP_RET_KILL_PROCESS),
            statement(BPF_LD_W_ABS, 0),
            jump(libc::SYS_setsid as u32, 0, 1),
            statement(BPF_RET_K, SECCOMP_RET_ERRNO | libc::EPERM as u32),
            jump(libc::SYS_setpgid as u32, 0, 1),
            statement(BPF_RET_K, SECCOMP_RET_ERRNO | libc::EPERM as u32),
            statement(BPF_RET_K, SECCOMP_RET_ALLOW),
        ]
    }

    fn install_process_group_seccomp() -> std::io::Result<()> {
        let mut filter = process_group_seccomp_filter();
        let program = libc::sock_fprog {
            len: filter.len() as u16,
            filter: filter.as_mut_ptr(),
        };
        // SAFETY: program references a live array of valid classic BPF
        // instructions for the duration of prctl; NO_NEW_PRIVS was set first,
        // and the kernel copies the program before returning.
        if unsafe {
            libc::prctl(
                libc::PR_SET_SECCOMP,
                libc::SECCOMP_MODE_FILTER,
                &program as *const libc::sock_fprog,
            )
        } != 0
        {
            return Err(std::io::Error::last_os_error());
        }
        Ok(())
    }

    fn run_seccomp_test_helper() -> Result<()> {
        // SAFETY: PR_SET_NO_NEW_PRIVS accepts scalar arguments only; setting
        // it to 1 is irreversible for this subprocess.
        if unsafe { libc::prctl(libc::PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0) } != 0 {
            return Err(std::io::Error::last_os_error()).context("set test no_new_privs");
        }
        install_process_group_seccomp().context("install test seccomp filter")?;
        // SAFETY: setsid has no pointer arguments or preconditions.
        if unsafe { libc::setsid() } != -1
            || std::io::Error::last_os_error().raw_os_error() != Some(libc::EPERM)
        {
            anyhow::bail!("setsid was not denied with EPERM");
        }
        // SAFETY: pid and pgid zero are documented self/new-group sentinels.
        if unsafe { libc::setpgid(0, 0) } != -1
            || std::io::Error::last_os_error().raw_os_error() != Some(libc::EPERM)
        {
            anyhow::bail!("setpgid was not denied with EPERM");
        }
        Ok(())
    }

    fn run_privileged_smoke_helper(cli: &Cli) -> Result<()> {
        // SAFETY: geteuid has no pointer arguments or preconditions.
        if unsafe { libc::geteuid() } != 0 {
            anyhow::bail!("privileged smoke helper requires effective uid 0");
        }
        verify_required_kernel_syscalls()?;
        let uid = resolve_uid(&cli.uid)?;
        let gid = resolve_gid(&cli.gid)?;
        if uid == 0 || gid == 0 {
            anyhow::bail!("privileged smoke target uid and gid must be non-zero");
        }
        let namespace = cli
            .smoke_namespace
            .as_deref()
            .context("privileged smoke namespace is missing")?;
        let target = cli
            .smoke_target
            .as_ref()
            .context("privileged smoke target is missing")?;
        let namespace_fd = open_namespace(namespace)?;
        let identity = fd_identity(namespace_fd.as_raw_fd())?;
        drop(namespace_fd);
        let request = LaunchRequest {
            generation: "smoke".into(),
            mirror: "smoke".into(),
            operation: "sync".into(),
            namespace: namespace.into(),
            plan: tunasync_netns::LaunchPlan {
                argv: vec![target.to_string_lossy().into_owned()],
                cwd: "/tmp".into(),
                env: std::collections::BTreeMap::from([
                    ("EXPECTED_UID".into(), uid.to_string()),
                    ("EXPECTED_GID".into(), gid.to_string()),
                    ("EXPECTED_NETNS_DEV".into(), identity.dev.to_string()),
                    ("EXPECTED_NETNS_INO".into(), identity.ino.to_string()),
                ]),
            },
        };
        launch_pinned(request, identity, uid, gid)
    }

    fn validate_netns_root() -> Result<()> {
        let metadata = std::fs::symlink_metadata("/run/netns").context("stat /run/netns")?;
        if !metadata.is_dir()
            || metadata.file_type().is_symlink()
            || metadata.uid() != 0
            || metadata.permissions().mode() & 0o022 != 0
        {
            anyhow::bail!("/run/netns must be a root-owned directory not writable by group/other");
        }
        Ok(())
    }

    fn open_namespace(name: &str) -> Result<OwnedFd> {
        tunasync_netns::validate_namespace_name(name).map_err(anyhow::Error::msg)?;
        validate_netns_root()?;
        let root = open_raw(
            c"/run/netns",
            libc::O_RDONLY | libc::O_DIRECTORY | libc::O_CLOEXEC | libc::O_NOFOLLOW,
        )
        .context("open /run/netns")?;
        let c_name = CString::new(name)?;
        // SAFETY: root is an owned directory fd and c_name is a live,
        // NUL-terminated single component; flags forbid symlink traversal.
        let fd = unsafe {
            libc::openat(
                root.as_raw_fd(),
                c_name.as_ptr(),
                libc::O_RDONLY | libc::O_CLOEXEC | libc::O_NOFOLLOW,
            )
        };
        if fd < 0 {
            return Err(std::io::Error::last_os_error())
                .with_context(|| format!("open network namespace {name:?}"));
        }
        // SAFETY: fd is the newly returned non-negative descriptor and has no
        // other Rust owner.
        let fd = unsafe { OwnedFd::from_raw_fd(fd) };
        reject_host_namespace(fd.as_raw_fd())?;
        Ok(fd)
    }

    fn reject_host_namespace(fd: RawFd) -> Result<()> {
        let host_fd = open_raw(c"/proc/self/ns/net", libc::O_RDONLY | libc::O_CLOEXEC)
            .context("open host network namespace")?;
        if fd_identity(fd)? == fd_identity(host_fd.as_raw_fd())? {
            anyhow::bail!("configured namespace resolves to the host network namespace");
        }
        Ok(())
    }

    fn open_directory(path: &str) -> Result<OwnedFd> {
        tunasync_netns::validate_absolute_normalized_path(path, "cwd")
            .map_err(anyhow::Error::msg)?;
        let mut current = open_raw(
            c"/",
            libc::O_RDONLY | libc::O_DIRECTORY | libc::O_CLOEXEC | libc::O_NOFOLLOW,
        )?;
        for component in std::path::Path::new(path).components() {
            let std::path::Component::Normal(component) = component else {
                continue;
            };
            let component = CString::new(component.as_bytes())?;
            // SAFETY: current is an owned directory fd and component is a live
            // NUL-terminated path component; flags require a non-symlink dir.
            let next = unsafe {
                libc::openat(
                    current.as_raw_fd(),
                    component.as_ptr(),
                    libc::O_RDONLY | libc::O_DIRECTORY | libc::O_CLOEXEC | libc::O_NOFOLLOW,
                )
            };
            if next < 0 {
                return Err(std::io::Error::last_os_error())
                    .with_context(|| format!("open cwd {path} without symlinks"));
            }
            // SAFETY: next is the newly returned non-negative descriptor and
            // ownership is transferred exactly once into OwnedFd.
            current = unsafe { OwnedFd::from_raw_fd(next) };
        }
        Ok(current)
    }

    fn open_executable(path: &str) -> Result<OwnedFd> {
        tunasync_netns::validate_absolute_normalized_path(path, "executable")
            .map_err(anyhow::Error::msg)?;
        validate_controlled_path(std::path::Path::new(path))?;
        let canonical = std::fs::canonicalize(path)
            .with_context(|| format!("canonicalize executable {path:?}"))?;
        validate_controlled_path(&canonical)?;
        let relative = canonical
            .strip_prefix("/")
            .context("canonical executable is not absolute")?;
        let root = open_raw(c"/", libc::O_PATH | libc::O_DIRECTORY | libc::O_CLOEXEC)?;
        let relative = CString::new(relative.as_os_str().as_bytes())?;
        let how = OpenHow {
            flags: (libc::O_RDONLY | libc::O_CLOEXEC) as u64,
            mode: 0,
            resolve: RESOLVE_BENEATH | RESOLVE_NO_MAGICLINKS | RESOLVE_NO_SYMLINKS,
        };
        // SAFETY: root and relative identify live objects, how matches the
        // openat2 ABI and remains live, and the exact structure size is passed.
        let fd = unsafe {
            libc::syscall(
                libc::SYS_openat2,
                root.as_raw_fd(),
                relative.as_ptr(),
                &how,
                std::mem::size_of::<OpenHow>(),
            )
        } as i32;
        if fd < 0 {
            return Err(std::io::Error::last_os_error())
                .with_context(|| format!("pin executable {path:?} with openat2"));
        }
        // SAFETY: fd is the newly returned non-negative descriptor and has no
        // other Rust owner.
        let fd = unsafe { OwnedFd::from_raw_fd(fd) };
        let metadata = File::from(fd.try_clone()?).metadata()?;
        validate_executable_metadata(
            metadata.is_file(),
            metadata.uid(),
            metadata.permissions().mode(),
        )?;
        let mut header = [0_u8; 4];
        // SAFETY: fd is open for reading and header is valid writable storage
        // of header.len() bytes; offset zero is within the file ABI.
        let read =
            unsafe { libc::pread(fd.as_raw_fd(), header.as_mut_ptr().cast(), header.len(), 0) };
        if read != header.len() as isize {
            return Err(std::io::Error::last_os_error()).context("read executable header");
        }
        validate_executable_header(&header)?;
        Ok(fd)
    }

    fn validate_executable_metadata(is_file: bool, uid: u32, mode: u32) -> Result<()> {
        if !is_file || uid != 0 || mode & 0o022 != 0 || mode & 0o111 == 0 {
            anyhow::bail!(
                "isolated executable must be a root-owned executable regular file not writable by group/other"
            );
        }
        Ok(())
    }

    fn validate_executable_header(header: &[u8; 4]) -> Result<()> {
        if header != b"\x7fELF" {
            anyhow::bail!(
                "isolated executable must be an ELF binary; shebang scripts are rejected because interpreter path resolution cannot be pinned safely"
            );
        }
        Ok(())
    }

    fn validate_controlled_path(path: &std::path::Path) -> Result<()> {
        let mut current = PathBuf::from("/");
        for component in path.components() {
            let std::path::Component::Normal(component) = component else {
                continue;
            };
            current.push(component);
            let metadata = std::fs::symlink_metadata(&current)
                .with_context(|| format!("inspect executable component {}", current.display()))?;
            if metadata.uid() != 0
                || (!metadata.file_type().is_symlink()
                    && metadata.permissions().mode() & 0o022 != 0)
            {
                anyhow::bail!(
                    "executable component {} must be root-owned and not group/other writable",
                    current.display()
                );
            }
        }
        Ok(())
    }

    #[repr(C)]
    struct OpenHow {
        flags: u64,
        mode: u64,
        resolve: u64,
    }

    const RESOLVE_NO_MAGICLINKS: u64 = 0x02;
    const RESOLVE_NO_SYMLINKS: u64 = 0x04;
    const RESOLVE_BENEATH: u64 = 0x08;

    fn sanitize_fds(preserve: RawFd) -> std::io::Result<()> {
        let lower_closed = preserve <= 3 || close_range(3, (preserve - 1) as u32).is_ok();
        let upper_closed = close_range((preserve + 1) as u32, u32::MAX).is_ok();
        if lower_closed && upper_closed {
            return Ok(());
        }
        // SAFETY: all-zero is a valid initial representation for rlimit before
        // getrlimit initializes both fields.
        let mut limit: libc::rlimit = unsafe { std::mem::zeroed() };
        // SAFETY: limit points to valid writable rlimit storage for the call.
        if unsafe { libc::getrlimit(libc::RLIMIT_NOFILE, &mut limit) } != 0 {
            return Err(std::io::Error::last_os_error());
        }
        let maximum = limit.rlim_cur.min(i32::MAX as libc::rlim_t) as RawFd;
        for fd in 3..maximum {
            // SAFETY: close accepts any integer fd; preserve is explicitly
            // skipped and EBADF is handled as an already-closed descriptor.
            if fd != preserve && unsafe { libc::close(fd) } != 0 {
                let error = std::io::Error::last_os_error();
                if error.raw_os_error() != Some(libc::EBADF) {
                    return Err(error);
                }
            }
        }
        Ok(())
    }

    fn close_range(first: u32, last: u32) -> std::io::Result<()> {
        if first > last {
            return Ok(());
        }
        // SAFETY: close_range accepts scalar bounds only; flags zero requests
        // the standard inclusive close operation.
        if unsafe { libc::syscall(libc::SYS_close_range, first, last, 0_u32) } == 0 {
            Ok(())
        } else {
            Err(std::io::Error::last_os_error())
        }
    }

    fn clear_capabilities() -> std::io::Result<()> {
        #[repr(C)]
        struct CapHeader {
            version: u32,
            pid: i32,
        }
        #[repr(C)]
        #[derive(Clone, Copy)]
        struct CapData {
            effective: u32,
            permitted: u32,
            inheritable: u32,
        }
        let mut header = CapHeader {
            version: 0x20080522,
            pid: 0,
        };
        let mut data = [CapData {
            effective: 0,
            permitted: 0,
            inheritable: 0,
        }; 2];
        // SAFETY: header/data match Linux capset ABI v3, target the calling
        // process, and point to live initialized storage for both u32 words.
        if unsafe { libc::syscall(libc::SYS_capset, &mut header, data.as_mut_ptr()) } != 0 {
            return Err(std::io::Error::last_os_error());
        }
        Ok(())
    }

    fn drop_capability_bounding_set() -> std::io::Result<()> {
        for capability in 0..=63 {
            // SAFETY: PR_CAPBSET_DROP accepts a scalar capability number; the
            // remaining zero arguments are required by the prctl ABI.
            if unsafe { libc::prctl(libc::PR_CAPBSET_DROP, capability, 0, 0, 0) } == 0 {
                continue;
            }
            let error = std::io::Error::last_os_error();
            if error.raw_os_error() == Some(libc::EINVAL) {
                break;
            }
            return Err(error);
        }
        Ok(())
    }

    fn terminate_and_reap(child: &mut Child) {
        terminate_group(child.id() as i32, CLEANUP_GRACE);
        let _ = child.kill();
        let _ = child.wait();
    }

    fn terminate_group(pgid: i32, grace: Duration) {
        signal_process_and_group(pgid, libc::SIGTERM);
        finish_group_termination(pgid, grace);
    }

    fn terminate_group_only(pgid: i32, grace: Duration) {
        // SAFETY: a negative pgid addresses the broker-owned process group;
        // SIGTERM has no pointer arguments and errors are intentionally ignored.
        unsafe {
            libc::kill(-pgid, libc::SIGTERM);
        }
        finish_group_termination(pgid, grace);
    }

    fn finish_group_termination(pgid: i32, grace: Duration) {
        let deadline = Instant::now() + grace;
        while Instant::now() < deadline {
            // SAFETY: signal zero probes existence of the broker-owned process
            // group and has no side effects or pointer arguments.
            if unsafe { libc::kill(-pgid, 0) } != 0 {
                return;
            }
            std::thread::sleep(Duration::from_millis(25));
        }
        // SAFETY: the negative pgid addresses only the broker-owned process
        // group; SIGKILL is the bounded-cleanup escalation.
        unsafe {
            libc::kill(-pgid, libc::SIGKILL);
        }
        let deadline = Instant::now() + Duration::from_secs(1);
        while Instant::now() < deadline {
            // SAFETY: signal zero probes existence of the broker-owned process
            // group and has no side effects or pointer arguments.
            if unsafe { libc::kill(-pgid, 0) } != 0 {
                return;
            }
            std::thread::sleep(Duration::from_millis(10));
        }
    }

    fn signal_process_and_group(pgid: i32, signal: i32) {
        // SAFETY: pgid is the helper pid/process-group id recorded at spawn;
        // both calls use scalar pid/signal ABI values. Sending to both closes
        // the pre-setpgid race without targeting unrelated processes.
        unsafe {
            libc::kill(-pgid, signal);
            libc::kill(pgid, signal);
        }
    }

    fn peer_has_event(stream: &UnixStream) -> Result<bool> {
        let mut pollfd = libc::pollfd {
            fd: stream.as_raw_fd(),
            events: libc::POLLIN | libc::POLLHUP | libc::POLLERR,
            revents: 0,
        };
        // SAFETY: pollfd points to one initialized entry for the duration of
        // poll and the UnixStream keeps its fd open.
        let result = unsafe { libc::poll(&mut pollfd, 1, 0) };
        if result < 0 {
            return Err(std::io::Error::last_os_error()).context("poll worker connection");
        }
        Ok(pollfd.revents & (libc::POLLIN | libc::POLLHUP | libc::POLLERR | libc::POLLNVAL) != 0)
    }

    fn peer_cred(stream: &UnixStream) -> Result<PeerCred> {
        // SAFETY: all-zero is a valid initial representation for ucred before
        // getsockopt initializes it.
        let mut cred: libc::ucred = unsafe { std::mem::zeroed() };
        let mut len = std::mem::size_of::<libc::ucred>() as libc::socklen_t;
        // SAFETY: stream keeps the fd open; cred and len are valid writable
        // buffers matching SO_PEERCRED's ucred ABI.
        if unsafe {
            libc::getsockopt(
                stream.as_raw_fd(),
                libc::SOL_SOCKET,
                libc::SO_PEERCRED,
                (&mut cred as *mut libc::ucred).cast(),
                &mut len,
            )
        } != 0
        {
            return Err(std::io::Error::last_os_error()).context("SO_PEERCRED");
        }
        Ok(PeerCred { uid: cred.uid })
    }

    fn fd_identity(fd: RawFd) -> Result<FileIdentity> {
        // SAFETY: all-zero is a valid initial representation for stat before
        // fstat initializes it.
        let mut stat: libc::stat = unsafe { std::mem::zeroed() };
        // SAFETY: fd is open for the caller's operation and stat points to
        // valid writable storage matching the platform ABI.
        if unsafe { libc::fstat(fd, &mut stat) } != 0 {
            return Err(std::io::Error::last_os_error()).context("fstat pinned file");
        }
        Ok(FileIdentity {
            dev: stat.st_dev,
            ino: stat.st_ino,
        })
    }

    fn open_raw(path: &CStr, flags: i32) -> std::io::Result<OwnedFd> {
        // SAFETY: path is a live NUL-terminated C string and flags require no
        // variadic mode argument because O_CREAT is never supplied here.
        let fd = unsafe { libc::open(path.as_ptr(), flags) };
        if fd < 0 {
            Err(std::io::Error::last_os_error())
        } else {
            // SAFETY: fd is the newly returned non-negative descriptor and has
            // no other Rust owner.
            Ok(unsafe { OwnedFd::from_raw_fd(fd) })
        }
    }

    fn cstring_vec(values: &[String], field: &str) -> Result<Vec<CString>> {
        values
            .iter()
            .map(|value| CString::new(value.as_bytes()).with_context(|| format!("NUL in {field}")))
            .collect()
    }

    fn cstring_ptrs(values: &[CString]) -> Vec<*const libc::c_char> {
        values
            .iter()
            .map(|value| value.as_ptr())
            .chain(std::iter::once(std::ptr::null()))
            .collect()
    }

    fn random_hex(bytes: usize) -> Result<String> {
        let mut random = vec![0_u8; bytes];
        // SAFETY: random exposes bytes of valid writable storage for exactly
        // random.len() bytes; flags zero request the standard blocking source.
        let read = unsafe { libc::getrandom(random.as_mut_ptr().cast(), random.len(), 0) };
        if read != random.len() as isize {
            return Err(std::io::Error::last_os_error()).context("getrandom");
        }
        Ok(random.iter().map(|byte| format!("{byte:02x}")).collect())
    }

    fn hex_digest(bytes: &[u8]) -> String {
        Sha256::digest(bytes)
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect()
    }

    fn constant_time_eq(left: &[u8], right: &[u8]) -> bool {
        left.len() == right.len()
            && left
                .iter()
                .zip(right)
                .fold(0_u8, |diff, (a, b)| diff | (a ^ b))
                == 0
    }

    fn exit_parts(status: ExitStatus) -> (Option<i32>, Option<i32>) {
        use std::os::unix::process::ExitStatusExt;
        (status.code(), status.signal())
    }

    fn send_error(stream: &mut UnixStream, kind: &str, message: &str) {
        let _ = tunasync_netns::write_frame(
            stream,
            &ServerFrame::Error {
                kind: kind.into(),
                message: message.into(),
            },
        );
    }

    fn resolve_uid(value: &str) -> Result<u32> {
        if let Ok(uid) = value.parse() {
            return Ok(uid);
        }
        let name = CString::new(value)?;
        // SAFETY: name is a live NUL-terminated C string; libc owns the returned
        // passwd storage and it is inspected immediately in this thread.
        let ptr = unsafe { libc::getpwnam(name.as_ptr()) };
        if ptr.is_null() {
            anyhow::bail!("unknown user {value:?}");
        }
        // SAFETY: the null case was rejected and pw_uid is a scalar field in
        // the libc-owned passwd record.
        Ok(unsafe { (*ptr).pw_uid })
    }

    fn resolve_gid(value: &str) -> Result<u32> {
        if let Ok(gid) = value.parse() {
            return Ok(gid);
        }
        let name = CString::new(value)?;
        // SAFETY: name is a live NUL-terminated C string; libc owns the returned
        // group storage and it is inspected immediately in this thread.
        let ptr = unsafe { libc::getgrnam(name.as_ptr()) };
        if ptr.is_null() {
            anyhow::bail!("unknown group {value:?}");
        }
        // SAFETY: the null case was rejected and gr_gid is a scalar field in
        // the libc-owned group record.
        Ok(unsafe { (*ptr).gr_gid })
    }

    #[cfg(test)]
    mod tests {
        use super::*;
        use std::io::Write;
        use std::os::unix::process::CommandExt;

        fn empty_runtime() -> RuntimePolicy {
            RuntimePolicy {
                policy: Policy {
                    generation: "g1".into(),
                    launch: Vec::new(),
                },
                sha256: "00".repeat(32),
                namespaces: HashMap::new(),
            }
        }

        fn shared(uid: u32, max_jobs: usize) -> Arc<Shared> {
            Arc::new(Shared {
                uid,
                gid: uid,
                max_jobs,
                read_timeout: Duration::from_secs(1),
                policy: PolicyStore::new(PathBuf::from("/nonexistent"), empty_runtime()),
                jobs: Mutex::new(JobRegistry::default()),
            })
        }

        #[test]
        fn non_root_controlled_policy_is_rejected() {
            let dir = tempfile::tempdir().unwrap();
            let path = dir.path().join("policy.json");
            std::fs::write(&path, br#"{"generation":"g","launch":[]}"#).unwrap();
            let mut mode = std::fs::metadata(&path).unwrap().permissions();
            mode.set_mode(0o666);
            std::fs::set_permissions(&path, mode).unwrap();
            assert!(load_policy(&path, true, false).is_err());
        }

        #[test]
        fn peer_uid_mismatch_is_rejected_before_request_parsing() {
            let (server, _client) = UnixStream::pair().unwrap();
            let actual_uid = peer_cred(&server).unwrap().uid;
            let error =
                handle_connection(server, &shared(actual_uid.wrapping_add(1), 1)).unwrap_err();
            assert!(error.to_string().contains("not authorized"));
        }

        #[test]
        fn executable_requires_root_control_and_accepts_system_symlink_components() {
            open_executable("/bin/true").expect("/bin symlink must resolve to pinned system ELF");
            let dir = tempfile::tempdir().unwrap();
            let path = dir.path().join("worker-owned");
            std::fs::copy("/bin/true", &path).unwrap();
            let mut permissions = std::fs::metadata(&path).unwrap().permissions();
            permissions.set_mode(0o755);
            std::fs::set_permissions(&path, permissions).unwrap();
            assert!(open_executable(path.to_str().unwrap()).is_err());
            let writable = dir.path().join("writable");
            std::fs::copy("/bin/true", &writable).unwrap();
            let mut permissions = std::fs::metadata(&writable).unwrap().permissions();
            permissions.set_mode(0o777);
            std::fs::set_permissions(&writable, permissions).unwrap();
            assert!(open_executable(writable.to_str().unwrap()).is_err());
            assert!(validate_executable_metadata(true, 0, 0o100777).is_err());
            assert!(validate_executable_metadata(true, 0, 0o100755).is_ok());
        }

        #[test]
        fn scripts_are_rejected_even_when_system_owned() {
            assert!(
                open_executable("/bin/sh").is_ok(),
                "/bin/sh is normally an ELF symlink target"
            );
            assert!(validate_executable_header(b"#!/b").is_err());
            assert!(validate_executable_header(b"\x7fELF").is_ok());
        }

        #[test]
        fn process_group_seccomp_filter_denies_only_escape_syscalls() {
            let filter = process_group_seccomp_filter();
            assert_eq!(filter.len(), 9);
            assert_eq!(filter[0].code, BPF_LD_W_ABS);
            assert_eq!(filter[0].k, 4);
            assert_eq!(filter[1].k, audit_arch());
            assert_eq!(filter[4].k, libc::SYS_setsid as u32);
            assert_eq!(filter[5].k, SECCOMP_RET_ERRNO | libc::EPERM as u32);
            assert_eq!(filter[6].k, libc::SYS_setpgid as u32);
            assert_eq!(filter[7].k, SECCOMP_RET_ERRNO | libc::EPERM as u32);
            assert_eq!(filter[8].k, SECCOMP_RET_ALLOW);
        }

        #[test]
        fn required_syscall_errors_distinguish_kernel_and_policy_failures() {
            assert_eq!(
                classify_required_syscall_error(&std::io::Error::from_raw_os_error(libc::ENOSYS)),
                RequiredSyscallError::Unsupported
            );
            assert_eq!(
                classify_required_syscall_error(&std::io::Error::from_raw_os_error(libc::EPERM)),
                RequiredSyscallError::Blocked
            );
            assert_eq!(
                classify_required_syscall_error(&std::io::Error::from_raw_os_error(libc::EBADF)),
                RequiredSyscallError::Unexpected
            );
        }

        #[test]
        fn job_capability_is_bound_to_uid_and_supervisor_control() {
            // SAFETY: geteuid has no pointer arguments or preconditions.
            let uid = unsafe { libc::geteuid() };
            let shared = shared(uid, 1);
            let (tx, rx) = mpsc::channel();
            shared.jobs.lock().unwrap().jobs.insert(
                "capability".into(),
                JobEntry {
                    uid,
                    key: ("m".into(), "sync".into()),
                    exclusive: true,
                    control: tx,
                },
            );
            let (mut server, mut client) = UnixStream::pair().unwrap();
            let thread = std::thread::spawn(move || {
                let SupervisorControl::Terminate(reply) = rx.recv().unwrap();
                reply.send(()).unwrap();
            });
            terminate_authorized(&mut server, PeerCred { uid }, "capability", &shared).unwrap();
            let frame: ServerFrame = tunasync_netns::read_frame(&mut client).unwrap();
            assert_eq!(frame, ServerFrame::Terminated);
            thread.join().unwrap();
        }

        #[test]
        fn admission_defaults_to_one_job_per_operation() {
            // SAFETY: geteuid has no pointer arguments or preconditions.
            let uid = unsafe { libc::geteuid() };
            let shared = shared(uid, 2);
            let key = ("mirror".to_string(), "sync".to_string());
            let mut jobs = shared.jobs.lock().unwrap();
            assert!(jobs.active_keys.insert(key.clone()));
            assert!(!jobs.active_keys.insert(key));
        }

        #[test]
        fn extra_post_launch_input_cleans_process_group_and_job_entry() {
            // SAFETY: geteuid has no pointer arguments or preconditions.
            let uid = unsafe { libc::geteuid() };
            let shared = shared(uid, 1);
            let key = ("mirror".to_string(), "sync".to_string());
            let job_id = "cleanup-capability".to_string();
            let (control_tx, control_rx) = mpsc::channel();
            {
                let mut jobs = shared.jobs.lock().unwrap();
                jobs.active_keys.insert(key.clone());
                jobs.jobs.insert(
                    job_id.clone(),
                    JobEntry {
                        uid,
                        key: key.clone(),
                        exclusive: true,
                        control: control_tx,
                    },
                );
            }
            let child = Command::new("/bin/sleep")
                .arg("30")
                .process_group(0)
                .stdout(Stdio::piped())
                .stderr(Stdio::piped())
                .spawn()
                .unwrap();
            let pgid = child.id() as i32;
            let mut supervisor =
                Supervisor::new(child, &shared, job_id.clone(), key.clone(), control_rx).unwrap();
            let (mut server, mut client) = UnixStream::pair().unwrap();
            client.write_all(b"unexpected").unwrap();
            supervisor.relay(&mut server).unwrap();
            assert!(!shared.jobs.lock().unwrap().jobs.contains_key(&job_id));
            // SAFETY: signal zero only probes the process group identified by
            // the child pid and has no pointer arguments or side effects.
            assert!(unsafe { libc::kill(-pgid, 0) } != 0);
        }

        #[test]
        fn saturated_output_queue_does_not_delay_cleanup_or_hold_job_slot() {
            // SAFETY: geteuid has no pointer arguments or preconditions.
            let uid = unsafe { libc::geteuid() };
            let shared = shared(uid, 1);
            let key = ("mirror".to_string(), "sync".to_string());
            let job_id = "saturated-output".to_string();
            let (control_tx, control_rx) = mpsc::channel();
            {
                let mut jobs = shared.jobs.lock().unwrap();
                jobs.active_keys.insert(key.clone());
                jobs.jobs.insert(
                    job_id.clone(),
                    JobEntry {
                        uid,
                        key: key.clone(),
                        exclusive: true,
                        control: control_tx,
                    },
                );
            }
            let child = Command::new("/usr/bin/yes")
                .process_group(0)
                .stdout(Stdio::piped())
                .stderr(Stdio::piped())
                .spawn()
                .unwrap();
            let mut supervisor =
                Supervisor::new(child, &shared, job_id.clone(), key.clone(), control_rx).unwrap();
            std::thread::sleep(Duration::from_millis(100));
            assert_eq!(
                supervisor.output_rx.try_iter().take(OUTPUT_QUEUE).count(),
                OUTPUT_QUEUE,
                "high-volume child did not saturate the bounded output queue"
            );
            std::thread::sleep(Duration::from_millis(20));

            let started = Instant::now();
            supervisor.cleanup();
            assert!(
                started.elapsed() < CLEANUP_GRACE + READER_JOIN_TIMEOUT,
                "cleanup exceeded its documented bound: {:?}",
                started.elapsed()
            );
            let jobs = shared.jobs.lock().unwrap();
            assert!(!jobs.jobs.contains_key(&job_id));
            assert!(!jobs.active_keys.contains(&key));
        }
    }
}
